#!/bin/bash

echo "Port to use for web server:"
read port

echo "Image name to use:"
read image

echo "Name for the container:"
read name

echo "Location of application files:"
read application

echo "Location of database files:"
read database

echo "Running container"
echo "docker run -p $port:80 –p 49801:6081 -v $application:/var/www -v $database:/var/lib/mysql --name $name $image"

#docker run -d -p 8001:80 -p 8002:6081 -p 2221:22 -p 3306:3306 -v /Users/luis/Code/drupal:/var/www -v /Users/luis/Docker/dbdata:/var/lib/mysql luis/drupal