#!/bin/bash
# default values
por="49800"
imag="drupal"
nam="rvmn"
applicatio="/var/www/"
databas="/var/lib/mysql"

read -p "Port to use [$por]:" port
port=${port:-$imag}

read -p "Name of the user [$nam]:" name
name=${name:-$nam}

read -p "Image name [$imag]:" image
image=${image:-$imag}

read -p "Location of application files [$applicatio]:" application
application=${application:-$applicatio}

read -p "Location of database files [$databas]:" database
database=${database:-$databas}

echo "Running container"
echo "docker run -p $port:80 –p 49801:6081 -v $application:/var/www -v $database:/var/lib/mysql --name $name/$image"
echo "docker run -p $port:80 –p 49801:6081 -v $application:/var/www -v $database:/var/lib/mysql --name $name/$image" | bash -l


#docker run -d -p 8001:80 -p 8002:6081 -p 2221:22 -p 3306:3306 -v /Users/luis/Code/drupal:/var/www -v /Users/luis/Docker/dbdata:/var/lib/mysql luis/drupal
